Repository IDAES/examples, pull requests merged in 2023-11, with the labels that each got.

#66 Add Jupyter Notebook for fixed bed 0D TSA
  idaes_examples/notebooks/_toc.yml
  idaes_examples/notebooks/docs/flowsheets/temperature_swing_adsorption/index.md
  idaes_examples/notebooks/docs/flowsheets/temperature_swing_adsorption/temperature_swing_adsorption.ipynb
  idaes_examples/notebooks/docs/flowsheets/temperature_swing_adsorption/temperature_swing_adsorption_doc.ipynb
  idaes_examples/notebooks/docs/flowsheets/temperature_swing_adsorption/temperature_swing_adsorption_test.ipynb
  idaes_examples/notebooks/docs/flowsheets/temperature_swing_adsorption/temperature_swing_adsorption_usr.ipynb
  idaes_examples/notebooks/docs/flowsheets/temperature_swing_adsorption/tsa_cycle.svg
Labels: Priority:Normal

#79 Updating Degeneracy Hunter example
  .github/actions/install/action.yml
  idaes_examples/notebooks/docs/diagnostics/degeneracy_hunter.ipynb
  idaes_examples/notebooks/docs/diagnostics/degeneracy_hunter_doc.ipynb
  idaes_examples/notebooks/docs/diagnostics/degeneracy_hunter_test.ipynb
  idaes_examples/notebooks/docs/diagnostics/degeneracy_hunter_usr.ipynb
Labels: Priority:Normal, documentation, enhancement

#81 Updating example to remove variable fixed outside bound
  idaes_examples/notebooks/docs/diagnostics/diagnostics_toolbox.ipynb
  idaes_examples/notebooks/docs/diagnostics/diagnostics_toolbox_doc.ipynb
  idaes_examples/notebooks/docs/diagnostics/diagnostics_toolbox_exercise.ipynb
  idaes_examples/notebooks/docs/diagnostics/diagnostics_toolbox_solution.ipynb
  idaes_examples/notebooks/docs/diagnostics/diagnostics_toolbox_test.ipynb
  idaes_examples/notebooks/docs/diagnostics/diagnostics_toolbox_usr.ipynb
Labels: Priority:High, bug
