Repository IDAES/examples, pull requests merged in 2024-05, with the labels that each got.

#101 Fix bug with "idaesx new" command for new directories
  idaes_examples/nbnew.py
  idaes_examples/notebooks/docs/power_gen/testnew/foo.ipynb
  idaes_examples/notebooks/docs/power_gen/testnew/foo_doc.ipynb
  idaes_examples/notebooks/docs/power_gen/testnew/foo_test.ipynb
  idaes_examples/notebooks/docs/power_gen/testnew/foo_usr.ipynb
Labels: Priority:High

#119 Add disclaimer about installation uninstalling IDAES
  README-developer.md
Labels: Priority:Normal

#106 Improve documentation for installation and pytest instructions
  README-developer.md
  README.md
  idaes_examples/browse.py
Labels: Priority:High, documentation, enhancement

#91 Liquid liquid extractor
  idaes_examples/notebooks/_toc.yml
  idaes_examples/notebooks/docs/unit_models/custom_unit_models/creating_unit_model.ipynb
  idaes_examples/notebooks/docs/unit_models/custom_unit_models/creating_unit_model_doc.ipynb
  idaes_examples/notebooks/docs/unit_models/custom_unit_models/creating_unit_model_test.ipynb
  idaes_examples/notebooks/docs/unit_models/custom_unit_models/creating_unit_model_usr.ipynb
  idaes_examples/notebooks/docs/unit_models/custom_unit_models/liquid_extraction/aqueous_property.py
  idaes_examples/notebooks/docs/unit_models/custom_unit_models/liquid_extraction/liq_liq_extractor_flowsheet.py
  idaes_examples/notebooks/docs/unit_models/custom_unit_models/liquid_extraction/liquid_liquid_extractor.py
  idaes_examples/notebooks/docs/unit_models/custom_unit_models/liquid_extraction/organic_property.py
  pyproject.toml
Labels: Priority:Normal

#117 Pandas deprecation for series call
  idaes_examples/notebooks/docs/param_est/parameter_estimation_nrtl_using_state_block.ipynb
  idaes_examples/notebooks/docs/param_est/parameter_estimation_nrtl_using_unit_model.ipynb
  idaes_examples/notebooks/docs/properties/parameter_estimation_pr.ipynb
Labels: Priority:Normal
